AllCops:
  TargetRubyVersion: 3.0.0

Layout/LineLength:
  Max: 120
  Exclude:
    - 'lib/tasks/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'integration/**/*'
    - '*.gemspec'
    - 'examples/app.rb'

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'
    - 'integration/**/*'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'integration/**/*'

Style/OptionalBooleanParameter:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: true
  EnforcedStyle: gemspec
