AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.0

plugins:
  - rubocop-rake
  - rubocop-rspec

Layout/LineLength:
  Max: 120
  Exclude:
    - lib/tasks/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - integration/**/*
    - "*.gemspec"
    - examples/app.rb

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Exclude:
    - spec/**/*
    - integration/**/*

Style/Documentation:
  Exclude:
    - spec/**/*
    - integration/**/*

Style/OptionalBooleanParameter:
  Enabled: false

Style/SelectByRegexp:
  Exclude:
    - lib/cotton_tail/middleware/router.rb

Gemspec/DevelopmentDependencies:
  Enabled: true
  EnforcedStyle: gemspec

RSpec/ExampleLength:
  Max: 10
  Exclude:
    - spec/integration/cotton_tail/app_spec.rb
    - spec/integration/dsl_integration_spec.rb

RSpec/MultipleExpectations:
  Enabled: false

RSpec/VerifiedDoubles:
  Exclude:
    - spec/integration/cotton_tail/app_spec.rb

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
    - given
    - when
    - with
    - without
    - and

RSpec/NestedGroups:
  Max: 4
